### ISSUE TITLE
Add stairs, slabs and walls of wool

### ISSUE THREAD

**Issue by MoriTanosuke** [MoriTanosuke/nadiamiona#10]
Maybe use a way to dynamically generate this blocks for all types of wool instead of manually creating the JSON files.

**Comment by MoriTanosuke** [comment]
Wool Stairs added in bdd343e323c864a211e7e38f7acc3f0d7f5a40cc and b9663d100d17fb4052a92e4e8f2325c19cf65301

**Comment by MoriTanosuke** [comment]
All colors for wool stairs added in 4b4fb64eeb210c88ec6cc4e2d5a89c926b5d727d

**Comment by Flyrija** [comment]
Rezept für Wool Walls müsste geändert werden oder evtl. die Wool Walls ganz raus? Im Moment benutzen sie das gleiche Rezept wie die Sofas von Crayfish und beides läßt sich derzeit dadurch nicht craften.

**Comment by MoriTanosuke** [comment]
Ich hatte die Rezepte in Commit fe755ed302ea93214ca66d67e1554d3c61890084 auskommentiert.
