### ISSUE TITLE
Ghost recipe for mossy cobble

### ISSUE THREAD

**Issue by Flyrija** [MoriTanosuke/nadiamiona#15]
There seems to be an old ghost recipe for mossy cobble left in the code. Item image is a checkered block. If you build the block and place it down, it's still checkered, but turns into the right block after mining it.

**Comment by MoriTanosuke** [comment]
In 1.9 the recipe for mossy cobblestone can be removed, because it's in vanilla. Mossy cobblestone walls are also in vanilla.

**Comment by MoriTanosuke** [comment]
Recipe removed from 1.10 code
