### ISSUE TITLE
Itemskalierung falsch

### ISSUE THREAD

**Issue by Flyrija** [MoriTanosuke/nadiamiona#23]
Alle Lebensmittel außer den Sandwiches sind zu groß skaliert. 

- Breadslice
- Toast
- Cooked Egg
- Egg Sandwich
- Bottle of Milk
- Beer
- Cocoa
- Shot
- Multivitamin Juice
- Egg Nogg

**Comment by MoriTanosuke** [comment]
Skalierung angepasst. Hier sind Screenshots der Items:

![2017-07-02_11 07 52](https://user-images.githubusercontent.com/105346/27768554-e64833b2-5f16-11e7-8c4e-8a06c46fe741.png)
![2017-07-02_11 07 54](https://user-images.githubusercontent.com/105346/27768555-e66d7942-5f16-11e7-8f8d-97f0bffad3f9.png)
![2017-07-02_11 07 56](https://user-images.githubusercontent.com/105346/27768556-e6710102-5f16-11e7-9149-68eb8f54bb7a.png)
![2017-07-02_11 07 58](https://user-images.githubusercontent.com/105346/27768558-e6910c5e-5f16-11e7-90f0-312135e344ae.png)
![2017-07-02_11 08 00](https://user-images.githubusercontent.com/105346/27768557-e6748b92-5f16-11e7-99a0-91905953ad6b.png)
