### ISSUE TITLE
No recipes for some blocks

### ISSUE THREAD

**Issue by MoriTanosuke** [MoriTanosuke/nadiamiona#3]
Missing recipes for
- parquet floors for all woods
- (leave, stone, brick) walls

**Comment by Flyrija** [comment]
parquet floor should be:

xox
oxo (original) 
xox

or  
xx (simple)
xx 
- also there are some parquet floors missing (birch, acacia, dark oak etc.)

the walls are like other walls:

ooo
xxx
xxx
- mossy stone brick, sandstone (all 3), and quarz walls are missing

**Comment by MoriTanosuke** [comment]
I'll go through https://github.com/MoriTanosuke/nadiamiona/blob/master/docs/ModRezepte_v1.7.2g.pdf and add all recipes in the order of the PDF.

**Comment by MoriTanosuke** [comment]
I'm still working on the spawners. I don't know yet how to create spawn eggs/spawners with the correct meta for zombies, skeletons and wither skeletons.

**Comment by MoriTanosuke** [comment]
Looks like http://minecraft.gamepedia.com/Data_values/Entity_IDs is the definite list of meta IDs.

**Comment by MoriTanosuke** [comment]
Spawn eggs are done, but spawners are still missing. 😞

**Comment by MoriTanosuke** [comment]
- [x] Bright parquet floor hat kein Rezept
- [x] Dark parquet floor hat kein Rezept
- [x] Acacia Bookshelf hat keinen Namen tile.BooksAcacia.name
- [x] Acacia Bookshelf wird mit Birch statt Acacia gebaut
- [x] Dark Oak Bookshelf hat keinen Namen tile.BooksDarkOak.name
- [x] Dark Oak Bookshelf wird mit Birch statt Dark Oak gebaut
- [x] Crate of Lapislazuli hat nur Rezept mit Crate, nicht mit Planks
- [x] Wool Wall hat keinen Namen tile.wool_wall.name
- [ ] Hedge ist grau statt grün
- [ ] Wool Stairs hat kein Rezept
- [ ] Small block hat kein Rezept
- [x] No recipe for battleaxe

**Comment by MoriTanosuke** [comment]
@Flyrija Was ist das Rezept für die Battleaxe? Eine Emeralaxt ist schon drin, mit 3 Emerals und 2 Diamonds.

**Comment by MoriTanosuke** [comment]
Battleaxe was not included, only EmeralAxe. Battle Axe now has recipe

    ###
    #*#
    0*0

![just_enough_items](https://cloud.githubusercontent.com/assets/105346/22173204/bdf02490-dfbb-11e6-9c80-2a80b7cd1297.png)

**Comment by MoriTanosuke** [comment]
Fixed most of the problems above. @Flyrija Please retest. 🌈 

[nadiamiona-1.8.9-20170121T0843609Z.jar.zip](https://github.com/MoriTanosuke/nadiamiona/files/721020/nadiamiona-1.8.9-20170121T0843609Z.jar.zip)

**Comment by Flyrija** [comment]
- [ ]  Hedge ist grau statt grün
- [x]  Wool Stairs hat kein Rezept
- [ ]  Small block hat kein Rezept -(war glaub ich auch nur ein Testblock von dir bisher oder?)
- [ ]  Stone Wall kann zusätzlich mit Diorit, Andesit, Granit + polished Varianten hergestellt werden, gewollt?
- [x]  Battle Axe hat keinen Namen
- [x]  Wall Rezepte geben alle nur 1 stk. aus anstatt 6 stk. (mir auch gegrade erst aufgefallen)
- [x]  Bar Rezepte sind noch etwas off ..
ooo
o--
oxx  würde als Rezept prima reichen bei 2 stk. output. (oben 2x slaps, unten 2x planks) 

Rest funktioniert prima.

**Comment by MoriTanosuke** [comment]
- *Small Block* war tatsächlich nur zum Testen. Rezept dafür füge ich erstmal nicht ein.
- Wieso die Hecke nicht grün ist, weiß ich noch nicht... da muss ich nochmal ein wenig suchen.
- Bei der *Stone Wall* hab ich nichts eingeschränkt, soll das Rezept nur mit Stone funktionieren?
