### ISSUE TITLE
Recipes missing/wrong/balancing issue

### ISSUE THREAD

**Issue by Flyrija** [MoriTanosuke/nadiamiona#35]
Version: 1.12.2-beta3
Sorry, had little time last two weeks...

- [x] Salmon Sandwich recipe is wrong/broken -> gives out Bacon Sandwich instead of Salmon Sandwich
- [x] Eggnog -> Exchange the Cooked Egg with a normal Egg should be ...tastier, less chunky? =)
- [x] Wool Wall still shows up but has no recipe. If needed, set the same recipe as a door? 
(do we even need wool walls? Maybe if we want to build an asylum? =D)
    OOX
    OOX
    OOX
- [x] Crate recipe works only with Oak Planks at the moment -> should use all wood planks
- [x] Bar recipes only give out 1 Bar instead of 2
- [x] Excavator needs 2x "Uncraftable Potion"? 
- [x] Beer needs in the recipe version for a single bottle 2x Seed and 1 "Uncraftable Potion" 
-> should be 1x Water Bottle and 1x Seed
- [x] Cocoa -> balancing issue with the two possible recipes, also maybe name it "Cocoa Drink"?
                  Version 1: 1 Bucket of Milk, 3 Bottles, 2 Sugar, 3 Cocoa Beans = 3x Cocoa
                  Version 2: 1 Bottle of Milk (= 3 Buckets of Milk + 2 Bottles), 1 Sugar, 1 Cocoa Bean = 1x Cocoa
Maybe it would be good to change the recipe completely? Bottle of Milk is quite expensive with 3 buckets of milk and two glass bottles. 

Just a sorting thing that's not that important I think. I've noticed that several items are all over the place in the creative tab (Bars, Parquet, Tools, Food) but perfectly ordered in JEI/NEI.

**Comment by MoriTanosuke** [comment]
Excavator recipe is only shown different in JEI, works with potions as intended. Same with beer, the water bottle is shown as "*uncraftable potion*".

**Comment by MoriTanosuke** [comment]
Wools walls removed.
