### ISSUE TITLE
Wrong recipe for Wood bar

### ISSUE THREAD

**Issue by Flyrija** [MoriTanosuke/nadiamiona#6]
The recipe for the wood bar is wrong (all colors).

atm:  
xxx   (slaps)
xox   (planks)
xxx   (planks)

should be:  
ooo
xxx (slaps)
xxx  (planks)

**Comment by MoriTanosuke** [comment]
The recipe for the plain wood bar is at https://github.com/MoriTanosuke/nadiamiona/blob/master/src/main/java/kalle/proxies/BasisCommonProxy.java#L182+L183

This is the current recipe:

```
GameRegistry.addRecipe(new ItemStack(theke), "BBB", "A0A", "AAA",
    'A', new ItemStack(Blocks.planks, 1, 0),
    'B', new ItemStack(Blocks.wooden_slab, 1, 0));
```

Guess I copied it from the crates. The following will fix the recipe:

```
GameRegistry.addRecipe(new ItemStack(theke), "0000", "BBB", "AAA",
    'A', new ItemStack(Blocks.planks, 1, 0),
    'B', new ItemStack(Blocks.wooden_slab, 1, 0));
```
